export function generateHeartTexture(fromx, fromy, tox, toy, lw, hlen, color, graphics: Phaser.GameObjects .Graphics) {
  graphics.clear()
  graphics.fillStyle(0xffffff)
  graphics.beginPath()
  graphics.moveTo(25, 75)
  graphics.lineTo(0, 52)
  graphics.lineTo(0, 50)
  graphics.lineTo(50, 50)
  graphics.lineTo(50, 52)
  graphics.lineTo(25, 75)
  graphics.closePath()
  graphics.fill()
  graphics.arc(12.5, 50, 12.5, 0, Math.PI, true, 0)
  graphics.arc(37.5, 50, 12.5, 0, Math.PI, true, 0)
  graphics.fillStyle(0xffffff)
  graphics.fill()
  graphics.generateTexture('heart', 50, 75)
  graphics.clear()

}